channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python
  - pytorch
  - cudatoolkit
  - pyyaml
  - pip
  - numpy
  - matplotlib
  - pip:
    - torch_tb_profiler
    - pytorch-lightning
    - torchmetrics
